-- Supabase Migration: Create billing_profiles table

CREATE TABLE IF NOT EXISTS public.billing_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    document_type TEXT NOT NULL CHECK (document_type IN ('DNI', 'RUC', 'CE')),
    document_number TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    fiscal_address TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique index to guarantee only one default billing profile per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_billing_default_per_user 
ON public.billing_profiles(profile_id) 
WHERE is_default = TRUE;

-- Enable RLS
ALTER TABLE public.billing_profiles ENABLE ROW LEVEL SECURITY;

-- Policies for billing_profiles
CREATE POLICY "Users can view their own billing profiles"
ON public.billing_profiles FOR SELECT
USING (profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can insert their own billing profiles"
ON public.billing_profiles FOR INSERT
WITH CHECK (profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their own billing profiles"
ON public.billing_profiles FOR UPDATE
USING (profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid()))
WITH CHECK (profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can delete their own billing profiles"
ON public.billing_profiles FOR DELETE
USING (profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid()));

-- Set up trigger to automatically update updated_at timestamp
CREATE TRIGGER update_billing_profiles_updated_at
BEFORE UPDATE ON public.billing_profiles
EXECUTE FUNCTION public.update_updated_at_column();

-- Add billing_profile snapshot column to existing orders table
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS billing_profile JSONB NOT NULL DEFAULT '{}'::jsonb;
