-- Content from orders_rpc.sql
-- ============================================================================
-- MasKot | Orders Module (orders_rpc.sql)
-- RPC Implementations
-- ============================================================================

-- ==========================================
-- 1. ENUMS
-- ==========================================
DO $$ BEGIN
    CREATE TYPE order_status AS ENUM ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE payment_method AS ENUM ('credit_card', 'debit_card', 'yape', 'plin', 'transfer');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE payment_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled', 'in_process', 'refunded', 'charged_back', 'in_mediation');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE card_brand AS ENUM ('visa', 'mastercard', 'amex', 'diners');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ==========================================
-- 2. TABLES
-- ==========================================

-- Direcciones de envío
CREATE TABLE IF NOT EXISTS shipping_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    recipient_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    address_line1 TEXT NOT NULL,
    address_line2 TEXT,
    district TEXT NOT NULL,
    province TEXT NOT NULL DEFAULT 'Lima',
    department TEXT NOT NULL DEFAULT 'Lima',
    postal_code TEXT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$ BEGIN 
    CREATE UNIQUE INDEX idx_unique_addresses_default_per_user ON shipping_addresses(profile_id) WHERE is_default = TRUE; 
EXCEPTION WHEN duplicate_table THEN null; WHEN SQLSTATE '42P07' THEN null; END $$;

-- Órdenes
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT REFERENCES profiles(id) ON DELETE SET NULL,
    status order_status NOT NULL DEFAULT 'pending',
    subtotal NUMERIC(10, 2) NOT NULL CHECK (subtotal >= 0),
    discount NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
    shipping_cost NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (shipping_cost >= 0),
    total NUMERIC(10, 2) NOT NULL CHECK (total >= 0),
    shipping_address JSONB NOT NULL DEFAULT '{}',
    payment_method payment_method NOT NULL,
    payment_status payment_status NOT NULL DEFAULT 'pending',
    transaction_id TEXT UNIQUE, -- ID final de la transacción bancaria
    checkout_id TEXT, -- Intención de pago o session ID de la pasarela
    contact_email TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Items de orden
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    sku TEXT NOT NULL, 
    selected_variant JSONB NOT NULL DEFAULT '{}'::jsonb, 
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10, 2) NOT NULL CHECK (unit_price > 0),
    is_subscription BOOLEAN NOT NULL DEFAULT FALSE,
    subscription_frequency_days INTEGER CHECK (subscription_frequency_days > 0)
);

-- Tokens de pago (Mercado Pago vault)
CREATE TABLE IF NOT EXISTS payment_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    token_id TEXT NOT NULL, 
    last_four TEXT NOT NULL,
    card_brand card_brand NOT NULL,
    expires_at TIMESTAMPTZ,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$ BEGIN 
    CREATE UNIQUE INDEX idx_unique_tokens_default_per_user ON payment_tokens(profile_id) WHERE is_default = TRUE;
EXCEPTION WHEN duplicate_table THEN null; WHEN SQLSTATE '42P07' THEN null; END $$;

-- ==========================================
-- 4. ATOMIC CHECKOUT RPC 
-- ==========================================

CREATE OR REPLACE FUNCTION create_order(
    p_profile_id BIGINT,
    p_cart_id BIGINT,
    p_shipping_address_id BIGINT,
    p_payment_method payment_method,
    p_checkout_id TEXT DEFAULT NULL,
    p_contact_email TEXT DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
    v_cart RECORD;
    v_address RECORD;
    v_order_id BIGINT;
    v_item JSONB;
    v_shipping_cost NUMERIC := 0;
    v_subtotal NUMERIC := 0;
    v_discount NUMERIC := 0;
    v_total NUMERIC := 0;
    v_email TEXT;
BEGIN
    -- 1. Validar Autenticación
    IF auth.uid() IS NULL OR NOT EXISTS (SELECT 1 FROM profiles WHERE id = p_profile_id AND user_id = auth.uid() AND deleted_at IS NULL) THEN
        RETURN jsonb_build_object('success', false, 'error', 'Not authorized');
    END IF;

    -- 2. Validar Carrito
    SELECT * INTO v_cart FROM carts WHERE id = p_cart_id AND profile_id = p_profile_id;
    IF v_cart IS NULL OR jsonb_array_length(v_cart.items) = 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'El carrito está vacío o no es válido');
    END IF;

    -- 3. Validar Dirección
    SELECT * INTO v_address FROM shipping_addresses WHERE id = p_shipping_address_id AND profile_id = p_profile_id;
    IF v_address IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Dirección de envío no encontrada');
    END IF;
    
    -- Utilizar costo de envío de zonas si existe, aquí omitiremos la lógica compleja asumiendo S/10 por default
    v_shipping_cost := 10.00;

    -- 4. Calcular montos 
    FOR v_item IN SELECT * FROM jsonb_array_elements(v_cart.items)
    LOOP
        v_subtotal := v_subtotal + ((v_item->>'price')::NUMERIC * (v_item->>'quantity')::INTEGER);
    END LOOP;
    
    v_total := v_subtotal + v_shipping_cost - v_discount; 
    
    -- 5. Resolver Email
    IF p_contact_email IS NOT NULL THEN
        v_email := p_contact_email;
    ELSE
        SELECT email INTO v_email FROM profiles WHERE id = p_profile_id;
    END IF;

    -- 6. Crear la orden central
    INSERT INTO orders (
        profile_id, status, subtotal, discount, shipping_cost, total, 
        shipping_address, payment_method, payment_status, contact_email, checkout_id
    ) VALUES (
        p_profile_id, 'pending', v_subtotal, v_discount, v_shipping_cost, v_total,
        row_to_json(v_address)::jsonb, p_payment_method, 'pending', v_email, p_checkout_id
    ) RETURNING id INTO v_order_id;

    -- 7. Insertar items
    FOR v_item IN SELECT * FROM jsonb_array_elements(v_cart.items)
    LOOP
        INSERT INTO order_items (
            order_id, product_id, product_name, sku, selected_variant,
            quantity, unit_price, is_subscription
        ) VALUES (
            v_order_id, 
            (v_item->>'product_id')::BIGINT, 
            v_item->>'name', 
            v_item->>'variant_sku', 
            COALESCE(v_item->'selected_variant', '{}'::jsonb),
            (v_item->>'quantity')::INTEGER, 
            (v_item->>'price')::NUMERIC, 
            (v_item->>'is_subscription')::BOOLEAN
        );
        -- Decrementar stock
        UPDATE products SET stock_quantity = stock_quantity - (v_item->>'quantity')::INTEGER
        WHERE id = (v_item->>'product_id')::BIGINT;
    END LOOP;

    -- 8. Limpiar Carrito
    UPDATE carts SET items = '[]'::jsonb, updated_at = NOW() WHERE id = p_cart_id;

    RETURN jsonb_build_object(
        'success', true,
        'order_id', v_order_id,
        'total', v_total
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
    
    -- RPC: Actualizar estado de orden con historial
    CREATE OR REPLACE FUNCTION update_order_status(
        p_order_id BIGINT,
        p_new_status order_status,
        p_notes TEXT DEFAULT NULL
    ) RETURNS JSONB AS $$
    BEGIN
        -- Actualizar orden
        UPDATE orders SET status = p_new_status, updated_at = NOW()
        WHERE id = p_order_id;
        
        -- Registrar en historial (obtener profile_id del auth.uid actual)
        INSERT INTO order_status_history (order_id, status, notes, created_by)
        VALUES (
            p_order_id, 
            p_new_status, 
            p_notes, 
            (SELECT id FROM profiles WHERE user_id = auth.uid() AND deleted_at IS NULL)
        );
        
        RETURN jsonb_build_object('success', true, 'order_id', p_order_id, 'new_status', p_new_status);
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
CREATE OR REPLACE FUNCTION add_order_shipment(
    p_order_id BIGINT,
    p_carrier TEXT,
    p_tracking_number TEXT
) RETURNS JSONB AS $$
DECLARE
    v_shipment_id BIGINT;
BEGIN
    -- Crear registro de envío
    INSERT INTO order_shipments (order_id, carrier, tracking_number, shipped_at)
    VALUES (p_order_id, p_carrier, p_tracking_number, NOW())
    RETURNING id INTO v_shipment_id;
    
    -- Actualizar estado de orden
    PERFORM update_order_status(p_order_id, 'shipped', 'Enviado con ' || p_carrier);
    
    RETURN jsonb_build_object('shipment_id', v_shipment_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Content from subscriptions_rpc.sql
-- ============================================================================
-- MasKot | Subscriptions Module (subscriptions_rpc.sql)
-- RPC Implementations
-- ============================================================================

-- RPC: Pausar suscripción (máx 2 meses)
CREATE OR REPLACE FUNCTION pause_subscription(
    p_subscription_id BIGINT,
    p_pause_days INTEGER DEFAULT 30
) RETURNS JSONB AS $$
DECLARE
    v_subscription RECORD;
    v_pause_until TIMESTAMPTZ;
BEGIN
    -- Validar máximo 60 días
    IF p_pause_days > 60 THEN
        RETURN jsonb_build_object('success', false, 'error', 'Máximo 60 días de pausa');
    END IF;
    
    -- Obtener suscripción
    SELECT * INTO v_subscription FROM subscriptions 
    WHERE id = p_subscription_id AND profile_id = (SELECT id FROM profiles WHERE user_id = auth.uid() AND deleted_at IS NULL);
    
    IF v_subscription IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Suscripción no encontrada');
    END IF;
    
    IF v_subscription.status != 'active' THEN
        RETURN jsonb_build_object('success', false, 'error', 'Solo se pueden pausar suscripciones activas');
    END IF;
    
    v_pause_until := NOW() + (p_pause_days || ' days')::INTERVAL;
    
    -- Actualizar suscripción
    UPDATE subscriptions 
    SET status = 'paused', pause_until = v_pause_until, updated_at = NOW()
    WHERE id = p_subscription_id;
    
    -- Registrar en historial
    INSERT INTO subscription_history (subscription_id, action, details)
    VALUES (p_subscription_id, 'paused', jsonb_build_object('pause_days', p_pause_days, 'pause_until', v_pause_until));
    
    RETURN jsonb_build_object('success', true, 'new_status', 'paused', 'pause_until', v_pause_until);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: Reanudar suscripción
CREATE OR REPLACE FUNCTION resume_subscription(p_subscription_id BIGINT)
RETURNS JSONB AS $$
DECLARE
    v_subscription RECORD;
    v_next_billing TIMESTAMPTZ;
BEGIN
    SELECT * INTO v_subscription FROM subscriptions 
    WHERE id = p_subscription_id AND profile_id = (SELECT id FROM profiles WHERE user_id = auth.uid() AND deleted_at IS NULL);
    
    IF v_subscription IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Suscripción no encontrada');
    END IF;
    
    IF v_subscription.status != 'paused' THEN
        RETURN jsonb_build_object('success', false, 'error', 'Solo se pueden reanudar suscripciones pausadas');
    END IF;
    
    v_next_billing := NOW() + (v_subscription.frequency_days || ' days')::INTERVAL;
    
    UPDATE subscriptions 
    SET status = 'active', pause_until = NULL, next_billing_date = v_next_billing, updated_at = NOW()
    WHERE id = p_subscription_id;
    
    INSERT INTO subscription_history (subscription_id, action, details)
    VALUES (p_subscription_id, 'resumed', jsonb_build_object('next_billing_date', v_next_billing));
    
    RETURN jsonb_build_object('success', true, 'new_status', 'active', 'next_billing_date', v_next_billing);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: Cancelar suscripción con motivo
CREATE OR REPLACE FUNCTION cancel_subscription(
    p_subscription_id BIGINT,
    p_cancellation_reason TEXT
) RETURNS JSONB AS $$
DECLARE
    v_subscription RECORD;
BEGIN
    SELECT * INTO v_subscription FROM subscriptions 
    WHERE id = p_subscription_id AND profile_id = (SELECT id FROM profiles WHERE user_id = auth.uid() AND deleted_at IS NULL);
    
    IF v_subscription IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Suscripción no encontrada');
    END IF;
    
    UPDATE subscriptions 
    SET status = 'cancelled', updated_at = NOW()
    WHERE id = p_subscription_id;
    
    INSERT INTO subscription_history (subscription_id, action, details)
    VALUES (p_subscription_id, 'cancelled', jsonb_build_object('reason', p_cancellation_reason));
    
    RETURN jsonb_build_object('success', true, 'cancelled_at', NOW());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: Adelantar próximo envío
CREATE OR REPLACE FUNCTION advance_next_shipment(p_subscription_id BIGINT)
RETURNS JSONB AS $$
DECLARE
    v_subscription RECORD;
    v_new_date TIMESTAMPTZ;
BEGIN
    SELECT * INTO v_subscription FROM subscriptions 
    WHERE id = p_subscription_id AND profile_id = (SELECT id FROM profiles WHERE user_id = auth.uid() AND deleted_at IS NULL);
    
    IF v_subscription IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Suscripción no encontrada');
    END IF;
    
    v_new_date := NOW() + INTERVAL '2 days'; -- Procesar en 2 días
    
    UPDATE subscriptions 
    SET next_billing_date = v_new_date, updated_at = NOW()
    WHERE id = p_subscription_id;
    
    RETURN jsonb_build_object('success', true, 'new_next_billing_date', v_new_date);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;



